DefaultContentLanguage = "en"
MetaDataFormat = "yaml"
Paginate = 10
SectionPagesMenu = "main"
baseURL = "/"
enableRobotsTXT = "true"
googleAnalytics = "UA-140050901-1"
languageCode = "en-us"
summarylength = 20
title = "ASP Productions"
[imaging]
anchor = "smart"
quality = 80
resampleFilter = "box"
[[menu.main]]
identifier = "updates"
name = "updates"
url = "/updates/"
weight = 2
[[menu.main]]
identifier = "testimonials"
name = "testimonials"
url = "/testimonials/"
weight = 4
[[menu.main]]
identifier = "contact"
name = "get in touch"
url = "/#contact"
weight = 1
[[menu.main]]
identifier = "about"
name = "about us"
url = "/about/"
weight = 3
[params]
background_color_class = "bg-black"
description = "ASP"
facebook = ""
favicon = "favicon.ico"
featured_image = "uploads/ac-train-track-bg.jpg"
github = ""
instagram = ""
linkedin = ""
recent_posts_number = 4
twitter = ""
youtube = ""
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
