DefaultContentLanguage = "en"
MetaDataFormat = "yaml"
Paginate = 10
SectionPagesMenu = "main"
baseURL = "/"
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-us"
summarylength = 20
title = "ASP"
[imaging]
anchor = "smart"
quality = 80
resampleFilter = "box"
[[menu.main]]
identifier = "updates"
name = "Updates"
url = "/updates/"
weight = 2
[[menu.main]]
identifier = "testimonials"
name = "Testimonials"
url = "/testimonials/"
weight = 4
[[menu.main]]
identifier = "contact"
name = "Get in touch"
url = "/#contact"
weight = 1
[[menu.main]]
identifier = "about"
name = "About Us"
url = "/about/"
weight = 3
[params]
background_color_class = "bg-black"
description = "ASP"
facebook = ""
favicon = ""
featured_image = "ac-train-track-bg.jpg"
github = ""
instagram = ""
linkedin = ""
recent_posts_number = 4
twitter = "https://twitter.com/"
youtube = ""
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
