DefaultContentLanguage = "en"
MetaDataFormat = "yaml"
Paginate = 10
SectionPagesMenu = "main"
baseURL = "www.ba-dev-s1.com"
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-us"
summarylength = 20
theme = "asp"
title = "ASP Productions"
[params]
background_color_class = "bg-black"
description = "ASP Productions"
facebook = ""
favicon = ""
featured_image = "http://mrmrs.github.io/photos/u/011.jpg"
github = ""
instagram = ""
linkedin = ""
recent_posts_number = 4
twitter = "https://twitter.com/"
youtube = ""
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
