# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "ASP Theme"
license = "MIT"
licenselink = "https://github.com/"
description = "A Base theme based off of Ananke Gohugo"
homepage = "https://github.com/"
tags = ["website", "responsive", "Disqus", "blog", "Tachyons"]
features = ["posts", "shortcodes", "related content", "comments"]
min_version = 0.10.1

[author]
  name = "Adam"
  homepage = "https://github.com/browna2"
