---
label: Default
hide_body: false
display_field: title
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: file
  name: default_feature_image
  label: feature image
  description: Feature image
- type: textarea
  name: default_description
  label: Description
  description: Secondary page information
  config:
    wysiwyg: true
    schema:
      format: markdown
- type: tag_list
  name: default_tags
  label: Tags
pages:
- content/testimonials/jonny-wright.md
- content/posts/our-search-for-writers.md
